test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage/files") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage", Rails.env, "files") %>

devminio:
  service: S3
  bucket: fizzy-dev-activestorage
  endpoint: "http://minio.localhost:39000"
  force_path_style: true
  request_checksum_calculation: when_required # default is when_supported with CRC64NVME checksum which FlashBlade doesn't support
  response_checksum_validation: when_required # default is when_supported with CRC64NVME checksum which FlashBlade doesn't support
  region: us-east-1 # default region required for signer
  access_key_id: minioadmin
  secret_access_key: minioadmin

aws:
  service: S3
  access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  bucket: <%= ENV["AWS_BUCKET"] || "fizzy-#{Rails.env}-activestorage" %>
  endpoint: <%= ENV["AWS_ENDPOINT"] %>
  force_path_style: <%= ENV["AWS_FORCE_PATH_STYLE"] == "true" %>
  region: <%= ENV.fetch("AWS_REGION", "us-east-1") %>
  secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
